server:
  port: 8888
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger%n %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger%n %msg%n"
  level:
    root: warn
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100MB

