server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elegant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    name: elegant
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: ElegantHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      timeout: 60000ms
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

mybatis-flex:
  global-config:
    print-banner: false
    key-config:
      key-type: auto
    logic-delete-column: deleted

logging:
  pattern:
    console: '%green(%d{HH:mm:ss}) %highlight(%-5level) %magenta(%logger%n) %msg%n'
  level:
    root: info
    p6spy: info
    org.hibernate: warn

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: '%(sqlSingleLine)'

proxy:
  rules:
    - target: http://localhost:8000
      path: /external/py
      timeout: 30