server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elegant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    name: elegant
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: ElegantHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
      password:
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0

logging:
  pattern:
    console: '%green(%d{HH:mm:ss}) %highlight(%-5level) %magenta(%logger%n) %msg%n'
  level:
    root: info
    p6spy: info
    org.hibernate: warn

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: '%(sqlSingleLine)'