server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elegant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
      password:
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0

logging:
  pattern:
    console: '%green(%d{HH:mm:ss}) %highlight(%-5level) %magenta(%logger%n) %msg%n'
  level:
    root: info
    p6spy: info
    org.hibernate: warn

